### ISSUE TITLE
How to set background color for flycheck and padding in the end?

### ISSUE THREAD

**Issue by conscious-puppet** [Lambda-Emacs/lambda-line#10]
The background color of flycheck and padding at the end in inactive modeline does not match with the rest of the modeline. How to change that. Also how to reduce the padding.

  
<img width="1512" alt="Screenshot 2022-11-05 at 2 06 17 PM" src="https://user-images.githubusercontent.com/46927550/200111456-a85b7bff-0d5c-4caf-8cc6-224d863215b0.png">

**Comment by mclearc** [comment]
I'm not seeing this so I suspect it is a function of the theme. The faces are all inherited. You can see them [here](https://github.com/Lambda-Emacs/lambda-line/blob/a3867b4935178507da624fb07b5bdb33005eed93/lambda-line.el#L637), and can change according to your theme.  I also do not have any problem with spacing at the end -- that is controlled by `lambda-line-hspace`. If you want to change the vertical padding use `lambda-line-space-top/bottom` .
