### ISSUE TITLE
right margin not compatible with olivetti-mode

### ISSUE THREAD

**Issue by cybershape** [Lambda-Emacs/lambda-line#12]
when olivetti-mode is enabed, the most right part is aligned with the olivetti-mode's right boundry as following image:

<img width="1224" alt="image" src="https://github.com/Lambda-Emacs/lambda-line/assets/105164/597a7567-4cff-4843-8ef6-dd1cfef524c2">

it should be aligned to the window as olivetti-mode disabled:

<img width="1227" alt="image" src="https://github.com/Lambda-Emacs/lambda-line/assets/105164/35e607fb-5ea8-4984-a3e4-7a135e13b5d9">

**Comment by mclearc** [comment]
Sorry for the late reply. I don't use olivetti-mode, but I suspect it is too eager in its application of margins. I will say that I use writeroom-mode,  which accomplishes the same function and does not have this problem. https://github.com/joostkremers/writeroom-mode

**Comment by mclearc** [comment]
I'm happy to take a pull-request to fix this, but it isn't going to be something I spend time on.
