### ISSUE TITLE
Add which-func-mode?

### ISSUE THREAD

**Issue by articuluxe** [Lambda-Emacs/lambda-line#14]
Are you interested in adding a "which-func-mode" display for prog-modes?

**Comment by mclearc** [comment]
Hi @articuluxe -- I think this could be fine though I don't use it. You'd probably have it displayed on the right. If you want to make a pull request please feel free to do so!

**Comment by articuluxe** [comment]
Thanks, I've made a pull request.

**Comment by articuluxe** [comment]
Friendly ping. :)

**Comment by articuluxe** [comment]
Thanks!
