### ISSUE TITLE
Doesn't render correctly when set to 'top

### ISSUE THREAD

**Issue by JordanAnthonyKing** [Lambda-Emacs/lambda-line#16]
When set to top the current buffer's headerline is blank but the other buffer's is correct. Changing buffers will make the old buffer have a correct headerline and the new buffer a blank one.

![image](https://github.com/user-attachments/assets/c0d1ec7a-70eb-4ea0-96df-2fa5027dc479)

Works when set to 'bottom:

![image](https://github.com/user-attachments/assets/b558bf5c-3b6a-461e-8a5a-1f93ba5bf899)

**Comment by mclearc** [comment]
Hi @JordanAnthonyKing  -- I'm not able to reproduce this with a clean install of emacs 29. If you're still seeing the problem can you tell me more about what version of emacs you're using and which os?

**Comment by JordanAnthonyKing** [comment]
I'm finding this works well now, not sure what was going on aside from it maybe being an issue on emacs 31.0.50 which has since been solved
