### ISSUE TITLE
Is possible configure lambda-line height?

### ISSUE THREAD

**Issue by damanis** [Lambda-Emacs/lambda-line#17]
Now lambda-line looks too big.
The options to set height of lambda-line or font-size and margins (top and bottom) should be useful.

**Comment by mclearc** [comment]
I'm not sure what you mean -- these options: 

```emacs-lisp
(setq lambda-line-space-top +.50)  ;; padding on top and bottom of line
(setq lambda-line-space-bottom -.50)
```

set the padding around the modeline text. If you want to change the size of the text itself that is something you do by changing the mode-line faces (though there a lambda-line faces as well) -- see the Emacs built-in function `describe-face`

**Comment by damanis** [comment]
You right. Probably I mistaken when trying theses parameters.
