### ISSUE TITLE
Question regarding changing the visual bell color

### ISSUE THREAD

**Issue by Kenneth-Mata** [Lambda-Emacs/lambda-line#5]
Hello, i'm curious regarding a way to change the color of the visual line, currently i'm using (custom-set-faces `(lambda-line-active ((t (:weight extrabold))))) but it doesn't completely color the bar as the regular visual bell does [like this](https://mega.nz/file/V5NgCS6A#11tqbPYY4rorDB89n_ET9QLmI00XnLwCwx_DbdlvKuM)

**Comment by mclearc** [comment]
Hi -- yes the face you want is `lambda-line-visual-bell` (you should be able to find it under `M-x describe face`). It's set to `red3` by default.

**Comment by Kenneth-Mata** [comment]
sorry, i pasted the wrong line, i'm using that face (custom-set-faces \`( \`(lambda-line-visual-bell ((t (:background "#470010" :weight extrabold))))) but i still have the situacion in the image, only part of the line is highlighted when the visual bell triggers

**Comment by mclearc** [comment]
Do you know if your theme sets the background color of the modeline? It's possible that the visual bell coloring is being overridden. Also, you probably don't need extrabold.

**Comment by Kenneth-Mata** [comment]
i checked at the source code of the theme (ef-themes) and it uses some weird mechanism to color the modeline, its okay if you want to close the issue
